version: '3.8'
services:
  devcontainer:
    build:
      context: .
      args:
        REPO_NAME: elifine-com
        APP_NAME: elifine
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/elifine-com:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts

      - python_infrastructure_venv:/workspaces/elifine-com/infrastructure/.venv
      # Break out the pnpm store folder as a separate docker volume for better performance on Windows hosts
      - pnpm_store:/workspaces/elifine-com/.pnpm-store
      # And node_modules
      - app_node_modules:/workspaces/elifine-com/elifine-com_app/node_modules
    command: sleep infinity
    ports:
      - "56219:2222"
    environment:
      - AWS_PROFILE=localstack


volumes:

  python_infrastructure_venv: {}
  pnpm_store: {}
  app_node_modules: {}
